'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import Link from 'next/link'
import Image from 'next/image'
import {
  FaCheckCircle,
  FaRocket,
  FaStar,
  FaChartLine,
  FaLink,
  FaFileAlt,
  FaWordpress,
  FaClock,
  FaPlug,
  FaChevronDown,
  FaArrowRight,
  FaQuoteLeft,
} from 'react-icons/fa'

const features = [
  {
    icon: <FaChartLine className="w-6 h-6" />,
    title: 'Smart SERP Analysis',
    description: 'Automatic analysis of top-ranking pages and integration of their keywords, titles, and data into your content.',
    benefits: ['Replicates what already works', 'Automatically integrates the right keywords'],
  },
  {
    icon: <FaLink className="w-6 h-6" />,
    title: 'Optimized Internal Linking',
    description: 'Relevant internal links integrated into your generated content. Pre-construction of internal links to optimize your semantic cocoons.',
    benefits: ['Smart link suggestions', 'SEO-optimized structure'],
  },
  {
    icon: <FaFileAlt className="w-6 h-6" />,
    title: 'Semantic Optimization',
    description: "ProAI Writer doesn&apos;t just place your main keywords. The AI analyzes the SERP and automatically integrates variations, synonyms, and entities.",
    benefits: ['Natural content flow', 'Google-friendly optimization'],
  },
  {
    icon: <FaStar className="w-6 h-6" />,
    title: 'SEO Score',
    description: "Optimize your content&apos;s SEO and receive concrete improvement suggestions. Confidently publish content perfectly optimized for SEO.",
    benefits: ['Clear score for each content', 'Concrete recommendations'],
  },
]

const integrations = [
  {
    icon: <FaWordpress className="w-8 h-8" />,
    title: 'Automatic Publishing',
    description: 'Publish directly to WordPress from ProAI Writer. Schedule your publications and manage multiple sites simultaneously.',
  },
  {
    icon: <FaClock className="w-8 h-8" />,
    title: 'Smart Update',
    badge: 'Coming soon',
    description: 'ProAI Writer automatically analyzes and updates your existing content to ensure its relevance and freshness long-term.',
  },
  {
    icon: <FaPlug className="w-8 h-8" />,
    title: 'Automatic Connection',
    description: 'Connect your WordPress site in a few clicks thanks to our official plugin. Simple, fast, and secure.',
  },
]

const testimonials = [
  {
    name: 'Sarah Johnson',
    role: 'SEO & Site Publisher',
    company: 'Digital Growth Agency',
    avatar: '👩‍💼',
    quote: "Relevant, SEO-optimized content that ranks well. ProAI Writer will leave a lasting mark on the AI writing landscape.",
  },
  {
    name: 'Michael Chen',
    role: 'Web Agency',
    company: 'TechFlow Solutions',
    avatar: '👨‍💻',
    quote: 'ProAI Writer is an excellent content creation tool. Its top-notch UX allows for advanced customization, generating quality text and especially creating them with our brand voice.',
  },
  {
    name: 'Emma Wilson',
    role: 'Site Publisher',
    company: 'ContentPro',
    avatar: '👩',
    quote: "This is no longer just AI writing, it&apos;s true art 🎨 Bravo, I&apos;ve never seen such a comprehensive tool.",
  },
  {
    name: 'David Martinez',
    role: 'Freelance SEO Expert',
    avatar: '👨',
    quote: 'SEO is evolving, and so are writing tools. ProAI Writer is the tool to use now. Save time and achieve faster results.',
  },
  {
    name: 'Lisa Anderson',
    role: 'Website Publisher & SEO',
    company: 'GrowthStack',
    avatar: '👩‍🦰',
    quote: 'As a web publisher, ProAI Writer addresses two essential challenges: generating text with a writing style that readers cannot identify as AI, and offering content that perfectly satisfies search engines.',
  },
  {
    name: 'James Thompson',
    role: 'Site Publisher',
    company: 'ContentMasters',
    avatar: '👨‍🦱',
    quote: 'As a user of several content generation tools, I can say that ProAI Writer is clearly above the rest. The UI is very user-friendly, and most importantly, the quality of the generated content is excellent.',
  },
]

const faqs = [
  {
    question: 'How Does ProAI Writer Work?',
    answer: 'ProAI Writer uses advanced AI to generate quality content. Simply enter your instructions, and the AI creates optimized text in seconds. The system combines multiple AI models, SERP analysis, and SEO best practices to deliver content that ranks and converts.',
  },
  {
    question: 'Can I Customize the Tone and Style?',
    answer: 'Yes! ProAI Writer allows you to create custom personas with specific writing styles, tones, and voices. You can define multiple personas for different brands or content types and apply them to your content generation.',
  },
  {
    question: 'Is the Content Unique?',
    answer: 'Absolutely! Every piece of content generated by ProAI Writer is unique and original. Our AI creates fresh content based on your specific instructions and keywords, ensuring it passes plagiarism checks and provides value to your readers.',
  },
  {
    question: 'What Types of Content Can I Create?',
    answer: 'ProAI Writer supports various content types including blog posts, product reviews, comparison articles, affiliate content, landing pages, and more. Each content type is optimized with specific templates and best practices.',
  },
  {
    question: 'How is SEO Managed?',
    answer: 'ProAI Writer includes built-in SEO optimization with SERP analysis, automatic keyword integration, internal linking suggestions, semantic optimization, and an SEO score for each piece of content. The AI analyzes top-ranking pages and incorporates winning strategies.',
  },
  {
    question: 'How Long Does it Take to Generate an Article?',
    answer: 'Generation time depends on article length and complexity. Most articles are generated in 30-90 seconds. Longer, more detailed content may take up to 2-3 minutes. The advanced generation mode with SERP analysis takes slightly longer but delivers superior results.',
  },
  {
    question: 'In which Languages Can ProAI Writer Generate Content?',
    answer: 'ProAI Writer supports 50+ languages including English, Spanish, French, German, Italian, Portuguese, Dutch, and many more. The AI maintains quality and natural flow across all supported languages.',
  },
  {
    question: 'Can I Change My Subscription at any Time?',
    answer: 'Yes! You can upgrade or downgrade your subscription at any time. Changes take effect immediately, and pricing is prorated. You can also purchase additional credits as needed for flexibility.',
  },
]

export default function LandingPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(0)

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100">
      {/* Navigation Header */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-white/95 backdrop-blur-lg border-b border-slate-200/80 shadow-sm">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-between h-16">
            {/* Logo */}
            <Link href="/" className="flex items-center gap-3 relative h-8">
              <div className="relative h-8 w-40">
                <Image 
                  src="/proai-writer.svg" 
                  alt="ProAI Writer logo" 
                  fill
                  className="object-contain" 
                  priority 
                />
              </div>
            </Link>

            {/* Navigation Links */}
            <nav className="hidden md:flex items-center gap-6">
              <a href="#features" className="text-slate-600 hover:text-indigo-600 transition-colors font-medium">
                Features
              </a>
              <a href="#testimonials" className="text-slate-600 hover:text-indigo-600 transition-colors font-medium">
                Testimonials
              </a>
              <a href="#faq" className="text-slate-600 hover:text-indigo-600 transition-colors font-medium">
                FAQ
              </a>
            </nav>

            {/* CTA Buttons */}
            <div className="flex items-center gap-3">
              <Link
                href="/login"
                className="rounded-full border border-slate-300 px-6 py-2 text-sm font-semibold text-slate-700 hover:border-indigo-300 hover:bg-indigo-50 transition-all"
              >
                Login
              </Link>
              <Link
                href="/register"
                className="rounded-full bg-gradient-to-r from-indigo-600 to-purple-600 px-6 py-2 text-sm font-semibold text-white shadow-lg shadow-indigo-500/50 transition-all hover:shadow-xl hover:shadow-indigo-500/60 hover:scale-105"
              >
                Try Free
              </Link>
            </div>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative overflow-hidden pt-16">
        {/* Animated background effects */}
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute -top-40 -right-40 w-80 h-80 bg-indigo-500/10 rounded-full blur-3xl animate-pulse" />
          <div className="absolute top-60 -left-40 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-pulse delay-1000" />
        </div>

        <div className="relative container mx-auto px-4 py-20 lg:py-32">
          {/* Update Badge */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex justify-center mb-8"
          >
            <div className="inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-indigo-50 px-4 py-2">
              <span className="flex h-2 w-2">
                <span className="absolute inline-flex h-2 w-2 animate-ping rounded-full bg-indigo-500 opacity-75"></span>
                <span className="relative inline-flex h-2 w-2 rounded-full bg-indigo-600"></span>
              </span>
              <span className="text-xs font-semibold uppercase tracking-wide text-indigo-600">Updates</span>
              <span className="text-sm text-slate-700">Native Integration with WordPress</span>
            </div>
          </motion.div>

          {/* Main Headline */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-center"
          >
            <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold text-slate-900 mb-6 leading-tight">
              With ProAI Writer, magically
              <br />
              <span className="bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
                generate your humanized content
              </span>
            </h1>
            <p className="text-xl md:text-2xl text-slate-600 mb-10 max-w-3xl mx-auto">
              Easily generate SEO articles that truly rank, without the hassle.
            </p>

            {/* CTA Button */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="mb-12"
            >
              <Link
                href="/dashboard"
                className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-indigo-600 to-purple-600 px-8 py-4 text-lg font-semibold text-white shadow-lg shadow-indigo-500/50 transition-all hover:shadow-xl hover:shadow-indigo-500/60 hover:scale-105"
              >
                <FaRocket />
                Start Creating Content
                <FaArrowRight className="w-4 h-4" />
              </Link>
            </motion.div>

            {/* Dashboard Preview */}
            <motion.div
              initial={{ opacity: 0, y: 40 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="mt-16"
            >
              <div className="relative mx-auto max-w-6xl">
                <div className="absolute -inset-4 bg-gradient-to-r from-indigo-500 to-purple-500 rounded-3xl blur-2xl opacity-20" />
                <div className="relative rounded-2xl border border-slate-200 bg-white p-2 shadow-2xl">
                  <img
                    src="/screenshots/dashboard.png"
                    alt="ProAI Writer Dashboard"
                    className="w-full rounded-xl"
                  />
                </div>
              </div>
            </motion.div>

            {/* Social Proof */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.4 }}
              className="mt-16 flex items-center justify-center gap-3"
            >
              <div className="flex -space-x-2">
                {['👨‍💼', '👩‍💻', '👨‍🎨', '👩‍🔬', '👨‍💻'].map((emoji, i) => (
                  <div
                    key={i}
                    className="inline-flex h-10 w-10 items-center justify-center rounded-full border-2 border-white bg-slate-100 text-lg shadow-sm"
                  >
                    {emoji}
                  </div>
                ))}
                <div className="inline-flex h-10 w-10 items-center justify-center rounded-full border-2 border-white bg-indigo-600 text-xs font-semibold text-white shadow-sm">
                  +650
                </div>
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-slate-900">+650 website publishers, SEO specialists, Agencies</p>
                <p className="text-xs text-slate-500">benefit from ProAI Writer&apos;s power</p>
              </div>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Overview Section */}
      <section className="relative py-20 bg-white">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <span className="inline-block text-xs font-semibold uppercase tracking-wide text-indigo-600 mb-4">
                Overview
              </span>
              <h2 className="text-4xl md:text-5xl font-bold text-slate-900 mb-6">
                Content designed for Google...
                <br />
                <span className="text-slate-600">and written for humans.</span>
              </h2>
              <p className="text-lg text-slate-600 mb-8">
                Generate SEO articles that truly perform! Not just for Google, but for your readers too. ProAI Writer
                combines AI, editorial strategy, and SEO common sense to create useful, readable, and well-ranked
                content.
              </p>
              <div className="space-y-3 mb-8">
                {[
                  'The right balance between SEO and readability',
                  'Useful articles, not just keyword-stuffed',
                  'An AI-powered engine + editorial expertise',
                ].map((item, i) => (
                  <div key={i} className="flex items-center gap-3">
                    <FaCheckCircle className="text-green-500 flex-shrink-0" />
                    <span className="text-slate-700">{item}</span>
                  </div>
                ))}
              </div>
              <Link
                href="/register"
                className="inline-flex items-center gap-2 rounded-full bg-indigo-600 px-6 py-3 font-semibold text-white transition-all hover:bg-indigo-700 hover:shadow-lg shadow-indigo-500/50"
              >
                <FaRocket />
                Get Started Free
              </Link>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.2 }}
            >
              <div className="rounded-3xl border border-slate-200 bg-white p-4 shadow-xl">
                <img
                  src="/screenshots/generate.png"
                  alt="Content Generation Interface"
                  className="w-full rounded-2xl"
                />
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="relative py-20 bg-gradient-to-b from-slate-50 to-white">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <span className="inline-block text-xs font-semibold uppercase tracking-wide text-indigo-600 mb-4">
              Features
            </span>
            <h2 className="text-4xl md:text-5xl font-bold text-slate-900 mb-4">
              Rank on the first page with integrated
              <br />
              SEO optimization
            </h2>
            <p className="text-lg text-slate-600 max-w-3xl mx-auto">
              Powerful features to optimize every aspect of your content and maximize your chances of reaching top
              results.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-8">
            {features.map((feature, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="rounded-3xl border border-slate-200 bg-white p-8 shadow-lg hover:shadow-xl hover:border-indigo-300 transition-all"
              >
                <div className="inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-600 to-purple-600 text-white mb-6">
                  {feature.icon}
                </div>
                <h3 className="text-2xl font-bold text-slate-900 mb-3">{feature.title}</h3>
                <p className="text-slate-600 mb-6">{feature.description}</p>
                <div className="space-y-2">
                  {feature.benefits.map((benefit, j) => (
                    <div key={j} className="flex items-center gap-2">
                      <FaCheckCircle className="text-green-500 flex-shrink-0" />
                      <span className="text-sm text-slate-700">{benefit}</span>
                    </div>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section id="testimonials" className="relative py-20 bg-white">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <span className="inline-block text-xs font-semibold uppercase tracking-wide text-indigo-600 mb-4">
              Testimonials
            </span>
            <h2 className="text-4xl md:text-5xl font-bold text-slate-900 mb-4">
              What Our Users Say
            </h2>
            <p className="text-lg text-slate-600">
              Trusted by content creators, publishers, and SEO professionals worldwide.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {testimonials.map((testimonial, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="rounded-3xl border border-slate-200 bg-white p-6 shadow-lg hover:shadow-xl transition-all"
              >
                <FaQuoteLeft className="text-indigo-200 text-3xl mb-4" />
                <p className="text-slate-700 mb-6 italic">&quot;{testimonial.quote}&quot;</p>
                <div className="flex items-center gap-3">
                  <div className="flex h-12 w-12 items-center justify-center rounded-full bg-slate-100 text-2xl">
                    {testimonial.avatar}
                  </div>
                  <div>
                    <p className="font-semibold text-slate-900">{testimonial.name}</p>
                    <p className="text-sm text-slate-500">{testimonial.role}</p>
                    {testimonial.company && (
                      <p className="text-xs text-slate-400">{testimonial.company}</p>
                    )}
                  </div>
                </div>
              </motion.div>
            ))}
          </div>

          <div className="mt-16 text-center">
            <div className="inline-flex items-center gap-2 rounded-full bg-indigo-50 px-6 py-3">
              <div className="flex -space-x-1">
                {[...Array(5)].map((_, i) => (
                  <FaStar key={i} className="text-yellow-400 w-5 h-5" />
                ))}
              </div>
              <span className="text-slate-900 font-semibold">4.9/5 reviews</span>
            </div>
            <p className="mt-4 text-slate-600">
              <strong className="text-slate-900">+650 website publishers, SEO specialists, Agencies</strong> benefit from
              ProAI Writer&apos;s power
            </p>
          </div>
        </div>
      </section>

      {/* Integrations Section */}
      <section className="relative py-20 bg-gradient-to-b from-slate-50 to-white">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <span className="inline-block text-xs font-semibold uppercase tracking-wide text-indigo-600 mb-4">
                Integrations
              </span>
              <h2 className="text-4xl md:text-5xl font-bold text-slate-900 mb-6">
                Export and Publish to Your Sites
              </h2>
              <p className="text-lg text-slate-600 mb-8">
                Export and publish your content directly from ProAI Writer to your WordPress sites or CMS.
              </p>

              <Link
                href="/register"
                className="inline-flex items-center gap-2 rounded-full bg-indigo-600 px-6 py-3 font-semibold text-white transition-all hover:bg-indigo-700 hover:shadow-lg shadow-indigo-500/50"
              >
                <FaRocket />
                Get Started
              </Link>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.2 }}
            >
              <div className="space-y-4">
                {integrations.map((integration, i) => (
                  <div
                    key={i}
                    className="rounded-3xl border border-slate-200 bg-white p-6 shadow-lg hover:shadow-xl transition-all"
                  >
                    <div className="flex items-start gap-4">
                      <div className="flex h-14 w-14 flex-shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-50 to-purple-50 text-indigo-600">
                        {integration.icon}
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-2">
                          <h3 className="text-xl font-bold text-slate-900">{integration.title}</h3>
                          {integration.badge && (
                            <span className="rounded-full bg-indigo-100 px-2 py-0.5 text-xs font-semibold text-indigo-700">
                              {integration.badge}
                            </span>
                          )}
                        </div>
                        <p className="text-slate-600">{integration.description}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="relative py-20 bg-white">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-16">
              <span className="inline-block text-xs font-semibold uppercase tracking-wide text-indigo-600 mb-4">
                FAQ
              </span>
              <h2 className="text-4xl md:text-5xl font-bold text-slate-900 mb-6">
                Frequently Asked Questions
              </h2>
              <p className="text-lg text-slate-600">
                Everything you need to know about ProAI Writer
              </p>
            </div>

            <div className="space-y-4">
              {faqs.map((faq, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.05 }}
                  className="rounded-2xl border border-slate-200 bg-white overflow-hidden shadow-sm hover:shadow-lg transition-all"
                >
                  <button
                    onClick={() => setOpenFaq(openFaq === i ? null : i)}
                    className="flex w-full items-center justify-between p-6 text-left transition-colors hover:bg-slate-50"
                  >
                    <span className="text-lg font-semibold text-slate-900 pr-4">{faq.question}</span>
                    <motion.div
                      animate={{ rotate: openFaq === i ? 180 : 0 }}
                      transition={{ duration: 0.2 }}
                      className="flex-shrink-0"
                    >
                      <FaChevronDown className="text-indigo-600" />
                    </motion.div>
                  </button>
                  <motion.div
                    initial={false}
                    animate={{
                      height: openFaq === i ? 'auto' : 0,
                      opacity: openFaq === i ? 1 : 0,
                    }}
                    transition={{ duration: 0.3 }}
                    className="overflow-hidden"
                  >
                    <p className="p-6 pt-0 text-slate-600">{faq.answer}</p>
                  </motion.div>
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Final CTA Section */}
      <section className="relative py-20 bg-gradient-to-br from-indigo-600 to-purple-600">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
                Start creating amazing content today
              </h2>
              <p className="text-xl text-white/90 mb-8">
                Join hundreds of content creators already using ProAI Writer to generate SEO-optimized articles.
              </p>

              <div className="flex items-center gap-3 mb-8">
                <div className="flex -space-x-2">
                  {['👨‍💼', '👩‍💻', '👨‍🎨', '👩‍🔬'].map((emoji, i) => (
                    <div
                      key={i}
                      className="inline-flex h-10 w-10 items-center justify-center rounded-full border-2 border-white bg-white/20 backdrop-blur-sm text-lg"
                    >
                      {emoji}
                    </div>
                  ))}
                  <div className="inline-flex h-10 w-10 items-center justify-center rounded-full border-2 border-white bg-white text-xs font-semibold text-indigo-600">
                    +650
                  </div>
                </div>
                <div className="text-sm text-white">
                  <p className="font-semibold">+650 happy users</p>
                  <p className="text-white/80">benefit from ProAI Writer&apos;s power</p>
                </div>
              </div>

              <Link
                href="/register"
                className="inline-flex items-center gap-2 rounded-full bg-white px-8 py-4 text-lg font-semibold text-indigo-600 shadow-lg transition-all hover:shadow-xl hover:scale-105"
              >
                <FaRocket />
                Get Started Free
                <FaArrowRight className="w-4 h-4" />
              </Link>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.2 }}
              className="hidden lg:block"
            >
              <div className="relative">
                <div className="absolute inset-0 bg-white/10 rounded-3xl blur-2xl" />
                <div className="relative rounded-2xl border border-white/20 bg-white/10 backdrop-blur-sm p-4">
                  <img
                    src="/screenshots/dashboard.png"
                    alt="ProAI Writer Interface"
                    className="w-full rounded-xl opacity-90"
                  />
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="relative py-16 bg-slate-900 border-t border-slate-800">
        <div className="container mx-auto px-4">
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8 mb-12">
            {/* Brand */}
            <div>
              <Link href="/" className="flex items-center mb-4 relative h-8">
                <div className="relative h-8 w-40 brightness-0 invert">
                  <Image 
                    src="/proai-writer.svg" 
                    alt="ProAI Writer logo" 
                    fill
                    className="object-contain" 
                  />
                </div>
              </Link>
              <p className="text-slate-400 text-sm">
                Generate SEO-optimized content that ranks and converts.
              </p>
            </div>

            {/* Quick Links */}
            <div>
              <h3 className="text-white font-semibold mb-4">Quick Links</h3>
              <ul className="space-y-2">
                {[
                  { label: 'Home', href: '/' },
                  { label: 'Features', href: '#features' },
                  { label: 'Testimonials', href: '#testimonials' },
                  { label: 'FAQ', href: '#faq' },
                ].map((link) => (
                  <li key={link.label}>
                    <a href={link.href} className="text-slate-400 hover:text-white transition-colors">
                      {link.label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>

            {/* Product */}
            <div>
              <h3 className="text-white font-semibold mb-4">Product</h3>
              <ul className="space-y-2">
                {[
                  { label: 'Dashboard', href: '/login' },
                  { label: 'Pricing', href: '/login' },
                  { label: 'API', href: '/login' },
                  { label: 'Integrations', href: '/login' },
                ].map((link) => (
                  <li key={link.label}>
                    <Link href={link.href} className="text-slate-400 hover:text-white transition-colors">
                      {link.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>

            {/* Newsletter */}
            <div>
              <h3 className="text-white font-semibold mb-4">Newsletter</h3>
              <p className="text-slate-400 text-sm mb-4">
                Get the latest updates and tips for content creation.
              </p>
              <form className="flex gap-2">
                <input
                  type="email"
                  placeholder="Your email"
                  className="flex-1 rounded-full bg-slate-800 border border-slate-700 px-4 py-2 text-sm text-white placeholder-slate-500 focus:border-indigo-500 focus:outline-none"
                />
                <button className="rounded-full bg-gradient-to-r from-indigo-600 to-purple-600 p-2 text-white hover:shadow-lg transition-all">
                  <FaArrowRight className="w-4 h-4" />
                </button>
              </form>
            </div>
          </div>

          <div className="border-t border-slate-800 pt-8 flex flex-col md:flex-row items-center justify-between gap-4">
            <p className="text-slate-400 text-sm">
              © 2025 ProAI Writer. All rights reserved.
            </p>
            <div className="flex gap-6">
              <a href="#" className="text-slate-400 hover:text-white transition-colors">
                Privacy
              </a>
              <a href="#" className="text-slate-400 hover:text-white transition-colors">
                Terms
              </a>
              <a href="#" className="text-slate-400 hover:text-white transition-colors">
                Contact
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
