'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import Link from 'next/link'
import {
  FaCheckCircle,
  FaRocket,
  FaStar,
  FaChartLine,
  FaLink,
  FaFileAlt,
  FaWordpress,
  FaClock,
  FaPlug,
  FaChevronDown,
  FaArrowRight,
  FaQuoteLeft,
  FaPlay,
} from 'react-icons/fa'

const features = [
  {
    icon: <FaChartLine className="w-6 h-6" />,
    title: 'Smart SERP Analysis',
    description: 'Automatic analysis of top-ranking pages and integration of their keywords, titles, and data into your content.',
    benefits: ['Replicates what already works', 'Automatically integrates the right keywords'],
  },
  {
    icon: <FaLink className="w-6 h-6" />,
    title: 'Optimized Internal Linking',
    description: 'Relevant internal links integrated into your Wisewand-generated content. Pre-construction of internal links to optimize your semantic cocoons.',
    benefits: ['Smart link suggestions', 'SEO-optimized structure'],
  },
  {
    icon: <FaFileAlt className="w-6 h-6" />,
    title: 'Semantic Optimization',
    description: "ProAI Writer doesn't just place your main keywords. The AI analyzes the SERP and automatically integrates variations, synonyms, and entities.",
    benefits: ['Natural content flow', 'Google-friendly optimization'],
  },
  {
    icon: <FaStar className="w-6 h-6" />,
    title: 'SEO Score',
    description: "Optimize your content's SEO and receive concrete improvement suggestions. Confidently publish content perfectly optimized for SEO.",
    benefits: ['Clear score for each content', 'Concrete recommendations'],
  },
]

const integrations = [
  {
    icon: <FaWordpress className="w-8 h-8" />,
    title: 'Automatic Publishing',
    description: 'Publish directly to WordPress from ProAI Writer. Schedule your publications and manage multiple sites simultaneously.',
  },
  {
    icon: <FaClock className="w-8 h-8" />,
    title: 'Smart Update',
    badge: 'Coming soon',
    description: 'ProAI Writer automatically analyzes and updates your existing content to ensure its relevance and freshness long-term.',
  },
  {
    icon: <FaPlug className="w-8 h-8" />,
    title: 'Automatic Connection',
    description: 'Connect your WordPress site in a few clicks thanks to our official plugin. Simple, fast, and secure.',
  },
]

const testimonials = [
  {
    name: 'Sarah Johnson',
    role: 'SEO & Site Publisher',
    company: 'Digital Growth Agency',
    avatar: '👩‍💼',
    quote: "Relevant, SEO-optimized content that ranks well. ProAI Writer will leave a lasting mark on the AI writing landscape.",
  },
  {
    name: 'Michael Chen',
    role: 'Web Agency',
    company: 'TechFlow Solutions',
    avatar: '👨‍💻',
    quote: 'ProAI Writer is an excellent content creation tool. Its top-notch UX allows for advanced customization, generating quality text and especially creating them with our brand voice.',
  },
  {
    name: 'Emma Wilson',
    role: 'Site Publisher',
    company: 'ContentPro',
    avatar: '👩',
    quote: "This is no longer just AI writing, it's true art 🎨 Bravo, I've never seen such a comprehensive tool.",
  },
  {
    name: 'David Martinez',
    role: 'Freelance SEO Expert',
    avatar: '👨',
    quote: 'SEO is evolving, and so are writing tools. ProAI Writer is the tool to use now. Save time and achieve faster results.',
  },
  {
    name: 'Lisa Anderson',
    role: 'Website Publisher & SEO',
    company: 'GrowthStack',
    avatar: '👩‍🦰',
    quote: 'As a web publisher, ProAI Writer addresses two essential challenges: generating text with a writing style that readers cannot identify as AI, and offering content that perfectly satisfies search engines.',
  },
  {
    name: 'James Thompson',
    role: 'Site Publisher',
    company: 'ContentMasters',
    avatar: '👨‍🦱',
    quote: 'As a user of several content generation tools, I can say that ProAI Writer is clearly above the rest. The UI is very user-friendly, and most importantly, the quality of the generated content is excellent.',
  },
]

const faqs = [
  {
    question: 'How Does ProAI Writer Work?',
    answer: 'ProAI Writer uses advanced AI to generate quality content. Simply enter your instructions, and the AI creates optimized text in seconds. The system combines multiple AI models, SERP analysis, and SEO best practices to deliver content that ranks and converts.',
  },
  {
    question: 'Can I Customize the Tone and Style?',
    answer: 'Yes! ProAI Writer allows you to create custom personas with specific writing styles, tones, and voices. You can define multiple personas for different brands or content types and apply them to your content generation.',
  },
  {
    question: 'Is the Content Unique?',
    answer: 'Absolutely! Every piece of content generated by ProAI Writer is unique and original. Our AI creates fresh content based on your specific instructions and keywords, ensuring it passes plagiarism checks and provides value to your readers.',
  },
  {
    question: 'What Types of Content Can I Create?',
    answer: 'ProAI Writer supports various content types including blog posts, product reviews, comparison articles, affiliate content, landing pages, and more. Each content type is optimized with specific templates and best practices.',
  },
  {
    question: 'How is SEO Managed?',
    answer: 'ProAI Writer includes built-in SEO optimization with SERP analysis, automatic keyword integration, internal linking suggestions, semantic optimization, and an SEO score for each piece of content. The AI analyzes top-ranking pages and incorporates winning strategies.',
  },
  {
    question: 'How Long Does it Take to Generate an Article?',
    answer: 'Generation time depends on article length and complexity. Most articles are generated in 30-90 seconds. Longer, more detailed content may take up to 2-3 minutes. The advanced generation mode with SERP analysis takes slightly longer but delivers superior results.',
  },
  {
    question: 'In which Languages Can ProAI Writer Generate Content?',
    answer: 'ProAI Writer supports 50+ languages including English, Spanish, French, German, Italian, Portuguese, Dutch, and many more. The AI maintains quality and natural flow across all supported languages.',
  },
  {
    question: 'Can I Change My Subscription at any Time?',
    answer: 'Yes! You can upgrade or downgrade your subscription at any time. Changes take effect immediately, and pricing is prorated. You can also purchase additional credits as needed for flexibility.',
  },
]

export default function LandingPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(0)

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      {/* Navigation Header */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-slate-900/80 backdrop-blur-lg border-b border-slate-700/50">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-between h-16">
            {/* Logo */}
            <Link href="/" className="flex items-center gap-2">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-500 to-indigo-500">
                <FaRocket className="text-white h-5 w-5" />
              </div>
              <span className="text-xl font-bold text-white">ProAI Writer</span>
            </Link>

            {/* Navigation Links */}
            <nav className="hidden md:flex items-center gap-6">
              <a href="#features" className="text-slate-300 hover:text-white transition-colors">
                Features
              </a>
              <a href="#testimonials" className="text-slate-300 hover:text-white transition-colors">
                Testimonials
              </a>
              <a href="#faq" className="text-slate-300 hover:text-white transition-colors">
                FAQ
              </a>
            </nav>

            {/* CTA Buttons */}
            <div className="flex items-center gap-3">
              <Link
                href="/login"
                className="rounded-full border border-slate-600 px-6 py-2 text-sm font-semibold text-white hover:border-slate-500 hover:bg-slate-800 transition-all"
              >
                Login
              </Link>
              <Link
                href="/register"
                className="rounded-full bg-gradient-to-r from-cyan-500 to-indigo-500 px-6 py-2 text-sm font-semibold text-white shadow-lg shadow-cyan-500/50 transition-all hover:shadow-xl hover:shadow-cyan-500/60"
              >
                Try Free
              </Link>
            </div>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative overflow-hidden pt-16">
        {/* Animated background effects */}
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute -top-40 -right-40 w-80 h-80 bg-indigo-500/20 rounded-full blur-3xl animate-pulse" />
          <div className="absolute top-60 -left-40 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl animate-pulse delay-1000" />
        </div>

        <div className="relative container mx-auto px-4 py-20 lg:py-32">
          {/* Update Badge */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex justify-center mb-8"
          >
            <div className="inline-flex items-center gap-2 rounded-full border border-cyan-500/30 bg-cyan-500/10 px-4 py-2 backdrop-blur-sm">
              <span className="flex h-2 w-2">
                <span className="absolute inline-flex h-2 w-2 animate-ping rounded-full bg-cyan-400 opacity-75"></span>
                <span className="relative inline-flex h-2 w-2 rounded-full bg-cyan-500"></span>
              </span>
              <span className="text-xs font-semibold uppercase tracking-wide text-cyan-400">Updates</span>
              <span className="text-sm text-slate-300">Native Integration with WordPress</span>
            </div>
          </motion.div>

          {/* Main Headline */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-center"
          >
            <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold text-white mb-6 leading-tight">
              With ProAI Writer, magically
              <br />
              <span className="bg-gradient-to-r from-cyan-400 to-indigo-400 bg-clip-text text-transparent">
                generate your humanized content
              </span>
            </h1>
            <p className="text-xl md:text-2xl text-slate-300 mb-10 max-w-3xl mx-auto">
              Easily generate SEO articles that truly rank, without the hassle.
            </p>

            {/* CTA Button */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
            >
              <Link
                href="/register"
                className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-cyan-500 to-indigo-500 px-8 py-4 text-lg font-semibold text-white shadow-lg shadow-cyan-500/50 transition-all hover:shadow-xl hover:shadow-cyan-500/60 hover:scale-105"
              >
                <FaRocket />
                Try Now
              </Link>
            </motion.div>

            {/* Social Proof */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.3 }}
              className="mt-12 flex items-center justify-center gap-3"
            >
              <div className="flex -space-x-2">
                {['👨‍💼', '👩‍💻', '👨‍🎨', '👩‍🔬', '👨‍💻'].map((emoji, i) => (
                  <div
                    key={i}
                    className="inline-flex h-10 w-10 items-center justify-center rounded-full border-2 border-slate-800 bg-slate-700 text-lg"
                  >
                    {emoji}
                  </div>
                ))}
                <div className="inline-flex h-10 w-10 items-center justify-center rounded-full border-2 border-slate-800 bg-slate-700 text-xs font-semibold text-slate-300">
                  +650
                </div>
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-white">+650 website publishers, SEO specialists, Agencies</p>
                <p className="text-xs text-slate-400">benefit from ProAI Writer's power</p>
              </div>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Overview Section */}
      <section className="relative py-20 bg-gradient-to-b from-slate-900 to-slate-800">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <span className="inline-block text-xs font-semibold uppercase tracking-wide text-cyan-400 mb-4">
                Overview
              </span>
              <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
                Content designed for Google...
                <br />
                <span className="text-slate-300">and written for humans.</span>
              </h2>
              <p className="text-lg text-slate-300 mb-8">
                Generate SEO articles that truly perform! Not just for Google, but for your readers too. ProAI Writer
                combines AI, editorial strategy, and SEO common sense to create useful, readable, and well-ranked
                content.
              </p>
              <div className="space-y-3 mb-8">
                {[
                  'The right balance between SEO and readability',
                  'Useful articles, not just keyword-stuffed',
                  'An AI-powered engine + editorial expertise',
                ].map((item, i) => (
                  <div key={i} className="flex items-center gap-3">
                    <FaCheckCircle className="text-cyan-400 flex-shrink-0" />
                    <span className="text-slate-200">{item}</span>
                  </div>
                ))}
              </div>
              <button className="inline-flex items-center gap-2 rounded-full bg-cyan-500 px-6 py-3 font-semibold text-white transition-all hover:bg-cyan-600">
                <FaPlay className="w-4 h-4" />
                View Presentation
              </button>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="relative"
            >
              <div className="rounded-3xl border border-slate-700 bg-slate-800/50 p-6 backdrop-blur-sm">
                <div className="aspect-video rounded-xl bg-gradient-to-br from-slate-700 to-slate-800 flex items-center justify-center">
                  <div className="text-center">
                    <div className="inline-flex h-20 w-20 items-center justify-center rounded-full bg-cyan-500/20 mb-4">
                      <FaPlay className="w-8 h-8 text-cyan-400" />
                    </div>
                    <p className="text-slate-300">Product Demo</p>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="relative py-20 bg-slate-800">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <span className="inline-block text-xs font-semibold uppercase tracking-wide text-cyan-400 mb-4">
              Features
            </span>
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
              Rank on the first page with integrated
              <br />
              SEO optimization
            </h2>
            <p className="text-lg text-slate-300 max-w-3xl mx-auto">
              Powerful features to optimize every aspect of your content and maximize your chances of reaching top
              results.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-8">
            {features.map((feature, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="rounded-3xl border border-slate-700 bg-slate-900/50 p-8 backdrop-blur-sm hover:border-cyan-500/50 transition-all"
              >
                <div className="inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-cyan-500 to-indigo-500 text-white mb-6">
                  {feature.icon}
                </div>
                <h3 className="text-2xl font-bold text-white mb-3">{feature.title}</h3>
                <p className="text-slate-300 mb-6">{feature.description}</p>
                <div className="space-y-2">
                  {feature.benefits.map((benefit, j) => (
                    <div key={j} className="flex items-center gap-2">
                      <FaCheckCircle className="text-cyan-400 flex-shrink-0" />
                      <span className="text-sm text-slate-300">{benefit}</span>
                    </div>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section id="testimonials" className="relative py-20 bg-gradient-to-b from-slate-900 to-slate-800">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <span className="inline-block text-xs font-semibold uppercase tracking-wide text-cyan-400 mb-4">
              Testimonials
            </span>
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
              Over 650 publishers satisfied with ProAI Writer.
            </h2>
            <p className="text-lg text-slate-300">
              They have saved time, gained traffic... and peace of mind.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {testimonials.map((testimonial, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.05 }}
                className="rounded-3xl border border-slate-700 bg-slate-900/50 p-6 backdrop-blur-sm"
              >
                <FaQuoteLeft className="text-cyan-400/40 text-2xl mb-4" />
                <p className="text-slate-300 mb-6 italic">{testimonial.quote}</p>
                <div className="flex items-center gap-3">
                  <div className="flex h-12 w-12 items-center justify-center rounded-full bg-slate-700 text-2xl">
                    {testimonial.avatar}
                  </div>
                  <div>
                    <p className="font-semibold text-white">{testimonial.name}</p>
                    <p className="text-sm text-slate-400">
                      {testimonial.role}
                      {testimonial.company && ` - ${testimonial.company}`}
                    </p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>

          <div className="text-center mt-12">
            <Link
              href="/register"
              className="inline-flex items-center gap-2 rounded-full bg-white px-8 py-4 font-semibold text-slate-900 transition-all hover:bg-slate-100"
            >
              Try ProAI Writer for Free
            </Link>
            <div className="mt-6 flex items-center justify-center gap-2">
              <div className="flex text-yellow-400">
                {[...Array(5)].map((_, i) => (
                  <FaStar key={i} className="w-5 h-5" />
                ))}
              </div>
              <span className="text-white font-semibold">4.9/5 reviews</span>
            </div>
            <p className="text-slate-400 mt-2">
              <strong className="text-white">+650 website publishers, SEO specialists, Agencies</strong> benefit from
              ProAI Writer's power
            </p>
          </div>
        </div>
      </section>

      {/* Integrations Section */}
      <section className="relative py-20 bg-slate-800">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <span className="inline-block text-xs font-semibold uppercase tracking-wide text-cyan-400 mb-4">
                Integrations
              </span>
              <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
                Native Integration with
                <br />
                WordPress
              </h2>
              <p className="text-lg text-slate-300 mb-8">
                Completely automate your content publishing and update workflow on your favorite CMS.
              </p>
              <Link
                href="/register"
                className="inline-flex items-center gap-2 rounded-full bg-cyan-500 px-6 py-3 font-semibold text-white transition-all hover:bg-cyan-600"
              >
                Start Installation
                <FaArrowRight />
              </Link>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="space-y-6"
            >
              {integrations.map((integration, i) => (
                <div
                  key={i}
                  className="rounded-3xl border border-slate-700 bg-slate-900/50 p-6 backdrop-blur-sm"
                >
                  <div className="flex items-start gap-4">
                    <div className="flex h-14 w-14 flex-shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-cyan-500/20 to-indigo-500/20 text-cyan-400">
                      {integration.icon}
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <h3 className="text-xl font-bold text-white">{integration.title}</h3>
                        {integration.badge && (
                          <span className="rounded-full bg-amber-500/20 px-3 py-1 text-xs font-semibold text-amber-400">
                            {integration.badge}
                          </span>
                        )}
                      </div>
                      <p className="text-slate-300">{integration.description}</p>
                    </div>
                  </div>
                </div>
              ))}
            </motion.div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="relative py-20 bg-gradient-to-b from-slate-900 to-slate-800">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-12">
            <div>
              <span className="inline-block text-xs font-semibold uppercase tracking-wide text-cyan-400 mb-4">
                FAQ
              </span>
              <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
                We answer all your
                <br />
                questions about <span className="text-cyan-400">ProAI Writer</span>
              </h2>
              <p className="text-lg text-slate-300">
                Do you have questions about how it works, credits, or subscriptions? We have it all covered. Here are
                the answers to the most frequently asked questions about ProAI Writer.
              </p>
            </div>

            <div className="space-y-4">
              {faqs.map((faq, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.05 }}
                  className="rounded-2xl border border-slate-700 bg-slate-900/50 backdrop-blur-sm overflow-hidden"
                >
                  <button
                    onClick={() => setOpenFaq(openFaq === i ? null : i)}
                    className="flex w-full items-center justify-between p-6 text-left transition-colors hover:bg-slate-800/50"
                  >
                    <span className="text-lg font-semibold text-white pr-4">{faq.question}</span>
                    <FaChevronDown
                      className={`flex-shrink-0 text-cyan-400 transition-transform ${
                        openFaq === i ? 'rotate-180' : ''
                      }`}
                    />
                  </button>
                  {openFaq === i && (
                    <motion.div
                      initial={{ height: 0 }}
                      animate={{ height: 'auto' }}
                      exit={{ height: 0 }}
                      className="border-t border-slate-700"
                    >
                      <p className="p-6 text-slate-300">{faq.answer}</p>
                    </motion.div>
                  )}
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Final CTA Section */}
      <section className="relative py-20 bg-gradient-to-br from-cyan-600 to-indigo-600">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
                Take action! Boost your visibility today!
              </h2>
              <p className="text-xl text-white/90 mb-8">
                <strong>Join over 650 publishers and agencies creating more effective, faster SEO content!</strong>{' '}
                Without sacrificing quality. Try ProAI Writer for free, with no commitment.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <Link
                  href="/register"
                  className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-8 py-4 text-lg font-semibold text-slate-900 transition-all hover:bg-slate-100"
                >
                  Try now
                  <FaArrowRight />
                </Link>
                <div className="flex items-center gap-3">
                  <div className="flex -space-x-2">
                    {['👨‍💼', '👩‍💻', '👨‍🎨', '👩'].map((emoji, i) => (
                      <div
                        key={i}
                        className="inline-flex h-10 w-10 items-center justify-center rounded-full border-2 border-white bg-white/20 text-lg backdrop-blur-sm"
                      >
                        {emoji}
                      </div>
                    ))}
                  </div>
                  <div className="text-sm text-white">
                    <p className="font-semibold">Over 650 site publishers, SEOs, Agencies</p>
                    <p className="text-white/80">benefit from ProAI Writer's power</p>
                  </div>
                </div>
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="relative"
            >
              <div className="rounded-3xl border border-white/20 bg-white/10 p-6 backdrop-blur-sm">
                <div className="aspect-video rounded-xl bg-gradient-to-br from-white/20 to-white/5 flex items-center justify-center">
                  <div className="text-center text-white">
                    <p className="text-lg font-semibold">Dashboard Preview</p>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="relative py-16 bg-slate-900 border-t border-slate-800">
        <div className="container mx-auto px-4">
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-12 mb-12">
            {/* Brand Column */}
            <div>
              <Link href="/" className="flex items-center gap-2 mb-4">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-500 to-indigo-500">
                  <FaRocket className="text-white h-5 w-5" />
                </div>
                <span className="text-xl font-bold text-white">ProAI Writer</span>
              </Link>
              <p className="text-slate-400 text-sm mb-4">
                ProAI Writer, simplified and ultra-powerful AI SEO writing.
              </p>
            </div>

            {/* Quick Links */}
            <div>
              <h3 className="text-white font-semibold mb-4">Quick Links</h3>
              <ul className="space-y-2">
                <li>
                  <a href="#features" className="text-slate-400 hover:text-cyan-400 transition-colors text-sm">
                    Features
                  </a>
                </li>
                <li>
                  <Link href="/buy-credits" className="text-slate-400 hover:text-cyan-400 transition-colors text-sm">
                    Pricing
                  </Link>
                </li>
                <li>
                  <a href="#faq" className="text-slate-400 hover:text-cyan-400 transition-colors text-sm">
                    FAQ
                  </a>
                </li>
              </ul>
            </div>

            {/* Legal */}
            <div>
              <h3 className="text-white font-semibold mb-4">Legal</h3>
              <ul className="space-y-2">
                <li>
                  <Link href="#" className="text-slate-400 hover:text-cyan-400 transition-colors text-sm">
                    Legal Notice
                  </Link>
                </li>
                <li>
                  <Link href="#" className="text-slate-400 hover:text-cyan-400 transition-colors text-sm">
                    Privacy Policy
                  </Link>
                </li>
                <li>
                  <Link href="#" className="text-slate-400 hover:text-cyan-400 transition-colors text-sm">
                    Terms of Service
                  </Link>
                </li>
              </ul>
            </div>

            {/* Newsletter */}
            <div>
              <h3 className="text-white font-semibold mb-4">Newsletter</h3>
              <p className="text-slate-400 text-sm mb-4">Receive our latest updates</p>
              <div className="flex gap-2">
                <input
                  type="email"
                  placeholder="Your email"
                  className="flex-1 rounded-full bg-slate-800 border border-slate-700 px-4 py-2 text-sm text-white placeholder-slate-500 focus:border-cyan-500 focus:outline-none"
                />
                <button className="rounded-full bg-gradient-to-r from-cyan-500 to-indigo-500 p-2 text-white hover:shadow-lg transition-all">
                  <FaArrowRight />
                </button>
              </div>
            </div>
          </div>

          {/* Bottom Bar */}
          <div className="border-t border-slate-800 pt-8 flex flex-col md:flex-row items-center justify-between gap-4">
            <p className="text-slate-500 text-sm">© 2025 ProAI Writer. All rights reserved.</p>
            <div className="flex items-center gap-4">
              <a
                href="#"
                className="text-slate-500 hover:text-cyan-400 transition-colors"
                aria-label="Email"
              >
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
                  <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
                </svg>
              </a>
              <a
                href="#"
                className="text-slate-500 hover:text-cyan-400 transition-colors"
                aria-label="YouTube"
              >
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z" />
                </svg>
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

